shpro/shapp/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin


urlpatterns = [
    path('', views.index, name='index'),
    path('user/admin/', admin.site.urls, name="admin"),
    path('about_us/', views.about_us, name="about_us"),
    path('contact_us/', views.contact_us, name="contact_us"),
    path('wisdom_page/', views.wisdom_page, name="wisdom_page"),
    path('book_lists/', views.book_lists, name="book_lists"),
    path('rent_lists/', views.rent_lists, name="rent_lists"),
    path('book_lists/<int:id>/', views.book_details, name="book_details"),
    path('book_post/', views.book_post, name="book_post"),
    path('search/', views.autocompleteModel, name="search"),
    path('profile/user/', views.UserPostListView.as_view(), name='user_posts'),
    path('user/<int:pk>/update/', views.PostUpdateView.as_view(), name='user_book_update'),
    path('user/<int:pk>/delete/', views.PostDeleteView.as_view(template_name='book_confirm_delete.html'),
         name='user_book_delete'),

    # cart functionality
    path('add-to-cart-<int:pro_id>/', views.AddToCartView.as_view(), name="addtocart"),
    path('my-cart/', views.MyCartView.as_view(), name="mycart"),
    path('manage-cart/<int:cp_id>/', views.ManageCartView.as_view(), name="managecart"),
    path('empty-cart/', views.EmptyCartView.as_view(), name="emptycart"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),

    path('user/signup/', views.signup, name='signup'),
    path('user/login/', views.login, name='login'),
    path('user/logout/', views.logout, name='logout'),
    path('ResetPassword/', views.ResetPassword, name='ResetPassword'),
    path('set-new-password/<uidb64>/<token>', views.Setnewpassword, name='set-new-password'),
    path('user/delete/', views.del_user, name='account_delete'),
    path('user/Feedback/', views.Feedback_user, name='Feedback_user'),
]

shpro/shpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shapp.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shpro/shapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
from django.urls import reverse


class books(models.Model):
    book_name = models.CharField(max_length=200)
    book_author = models.CharField(max_length=200)
    book_description = models.TextField(max_length=5000)
    book_image1 = models.ImageField(upload_to='book_images')
    book_image2 = models.ImageField(upload_to='book_images', blank=True, null=True)
    book_image3 = models.ImageField(upload_to='book_images', blank=True, null=True)
    book_image4 = models.ImageField(upload_to='book_images', blank=True, null=True)
    book_image5 = models.ImageField(upload_to='book_images', blank=True, null=True)
    book_price = models.IntegerField()
    is_rent = models.BooleanField(default=False)
    rent_days = models.CharField(max_length=100, blank=True, null=True)
    book_list_date = models.DateTimeField(default=datetime.now, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('user_posts')

    def __str__(self):
        return self.book_name


class Cart(models.Model):
    customer = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(books, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


class Feedback(models.Model):
    First_Name = models.CharField(max_length=200, null=True)
    Last_Name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    published_date = models.DateTimeField(default=datetime.now)
    May_we_contact_you = models.BooleanField(default=False)
    May_we_contact_you_with = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.First_Name} {self.Last_Name}'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    created_dates = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.user)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    created_at = models.DateTimeField(default=datetime.now())
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)


class SendMailRent(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL, blank=True, null=True)
    book_rent_time = models.CharField(max_length=100, blank=True, null=True)
    created_dates = models.DateTimeField(default=datetime.now())
    
    def __str__(self):
        return str(self.user)

shpro/shapp/forms.py
from django import forms
from .models import Order


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "mobile", "email"]

shpro/shapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, UpdateView, DeleteView, TemplateView, View, CreateView
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import send_mail
from validate_email import validate_email
import threading
from .forms import CheckoutForm
from .models import Feedback, books, Cart, CartProduct, Payment, Order, SendMailRent
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.conf import settings

import json
import requests
import stripe
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator

stripe.api_key = settings.STRIPE_SECRET_KEY

from datetime import datetime


# models

# threading

# This is for validate email (install like this pip install validate-email/ and also check check_regex=True,
# check_mx=True for if user enter not valid gmail account than throw the error)

# sending email

# reset password start here

# this is for online email verification


class EmailThread(threading.Thread):

    def __init__(self, email_message):
        self.email_message = email_message
        threading.Thread.__init__(self)

    def run(self):
        self.email_message.send()


class EcomMixin(object):
    def dispatch(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id")
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            if request.user.is_authenticated and request.user:
                cart_obj.customer = request.user
                cart_obj.save()
        return super().dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class AddToCartView(EcomMixin, TemplateView):
    template_name = "addtocart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get product id from requested url
        product_id = self.kwargs['pro_id']
        # get product
        product_obj = books.objects.get(id=product_id)

        # print(product_id, product_obj)

        # check if cart exists
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product=product_obj)
            # print(this_product_in_cart)

            # item already exists in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.book_price
                cartproduct.save()
                cart_obj.total += product_obj.book_price
                cart_obj.save()

            # new item is added in cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.book_price, quantity=1,
                    subtotal=product_obj.book_price)
                cart_obj.total += product_obj.book_price
                cart_obj.save()

        # check if cart does not exists
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                cart=cart_obj, product=product_obj, rate=product_obj.book_price, quantity=1,
                subtotal=product_obj.book_price)
            cart_obj.total += product_obj.book_price
            cart_obj.save()

        return context


@method_decorator(login_required, name='dispatch')
class MyCartView(EcomMixin, TemplateView):
    template_name = "mycart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context


@method_decorator(login_required, name='dispatch')
class ManageCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs["cp_id"]
        action = request.GET.get("action")
        # print(action)
        cp_obj = CartProduct.objects.get(id=cp_id)
        cart_obj = cp_obj.cart

        if action == "inc":
            cp_obj.quantity += 1
            cp_obj.subtotal += cp_obj.rate
            cp_obj.save()
            cart_obj.total += cp_obj.rate
            cart_obj.save()
        elif action == "dcr":
            cp_obj.quantity -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity == 0:
                cp_obj.delete()

        elif action == "rmv":
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
        else:
            pass
        return redirect("mycart")


@method_decorator(login_required, name='dispatch')
class EmptyCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            cart.cartproduct_set.all().delete()
            cart.total = 0
            cart.save()
        return redirect("mycart")


# class CheckoutView(EcomMixin, CreateView):
#     template_name = "checkout.html"
#     form_class = CheckoutForm
#     success_url = reverse_lazy("wisdom_page")
#
#     def dispatch(self, request, *args, **kwargs):
#         if request.user.is_authenticated and request.user:
#             pass
#         else:
#             return render(request, 'index.html')
#         return super().dispatch(request, *args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         cart_id = self.request.session.get("cart_id", None)
#         if cart_id:
#             cart_obj = Cart.objects.get(id=cart_id)
#         else:
#             cart_obj = None
#         context['cart'] = cart_obj
#         return context
#
#     def form_valid(self, form):
#         cart_id = self.request.session.get("cart_id")
#         if cart_id:
#             cart_obj = Cart.objects.get(id=cart_id)
#             form.instance.cart = cart_obj
#             form.instance.subtotal = cart_obj.total
#             form.instance.total = cart_obj.total
#             del self.request.session['cart_id']
#             order = form.save()
#
#         else:
#             return redirect("wisdom_page")
#         return super().form_valid(form)

class CheckoutView(EcomMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = self.request.session.get("cart_id", None)
        u_Form = CheckoutForm()
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None

        context = {
            'cart': cart_obj,
            'form': u_Form
        }
        return render(request, 'checkout.html', context)

    def post(self, request, *args, **kwargs):
        cart_id = self.request.session.get("cart_id")
        cart_obj = Cart.objects.get(id=cart_id)

        order = Order.objects.all()
        
        book_name = self.request.POST.get('bookName')
        Books_Days = self.request.POST.get('BooksDays')
        print(book_name, Books_Days)
        order_by1 = self.request.POST.get('ordered_by')
        shipping_address1 = self.request.POST.get('shipping_address')
        mobile1 = self.request.POST.get('mobile')
        email1 = self.request.POST.get('email')
        token = self.request.POST.get('stripeToken')

        user_email = self.request.user.email
        # print(user_email)

        # print(token)
        amount1 = int(cart_obj.total)
        # print(amount1)
        try:
            customer = stripe.Customer.create(
                email=email1,
                name=order_by1,
                source=token,
                address={
                    'line1': 'adres_users',
                    'postal_code': '56259',
                    'city': 'Mumbai',
                    'state': 'Mumbai',
                    'country': 'INDIA',
                },

            )

            charge = stripe.Charge.create(
                customer=customer,
                amount=amount1,
                currency='inr',
                description="classifieds Ads"

            )

            now_d = datetime.now()

            # create payment
            payments = Payment()
            payments.stripe_charge_id = charge['id']
            payments.user = self.request.user
            payments.amount = amount1
            payments.save()

            rb = SendMailRent()
            rb.user = self.request.user
            rb.book_rent_time = Books_Days
            rb.save()

            # assign payment to the order
            for ob in order:
                ob.cart = cart_obj
                ob.ordered_by = order_by1
                ob.shipping_address = shipping_address1
                ob.mobile = mobile1
                ob.email = email1
                ob.subtotal = amount1
                ob.total = amount1
                ob.payment_completed = True
                ob.save()

shpro/shapp/templates/book_confirm_delete.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	<title>Wisdom Pages: Welcome</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-social/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'sh_css/style.css' %}">

    <style>
      .column {
        float: left;
        width: 33.33%;
        padding: 5px;
      }

      /* Clear floats after image containers */
      .row::after {
        content: "";
        clear: both;
        display: table;
      }
    </style>

</head>


<body>
	<nav class="navbar navbar-dark navbar-expand-sm fixed-top">
		<div class="container">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
				<span class="navbar-toggler-icon"></span>
             </button>
             <a class="navbar-brand mr-auto" href=""><img src="{% static 'sh_images/logo.png' %}" height="30" width="35"></a>
             <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}"><span class="fa fa-sign-out"></span>Sign out</a></li>
                </ul>
            </div>
		</div>
	</nav>

	<div class="container">
        <br><br>
        <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'wisdom_page' %}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete</li>
              </ol>
            </nav>
          <br>
        <br>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the book "{{ object.book_name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'user_posts' %}">Cancel</a>
            </div>
        </form>

    </div>

	<script src="{% static 'node_modules/jquery/dist/jquery.slim.min.js' %}"></script>
	<script src="{% static 'node_modules/popper.js/dist/umd/popper.min.js' %}"></script>
	<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'sh_js/script.js' %}"></script>
</body>
</html>

shpro/shapp/templates/buy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Wisdom Pages: Buy books</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-social/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'sh_css/style.css' %}">
 	
</head>
<body>
	<nav class="navbar navbar-dark navbar-expand-sm fixed-top">
		<div class="container">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
				<span class="navbar-toggler-icon"></span>
             </button>
             <a class="navbar-brand mr-auto" href="wisdom.html"><img src="{% static 'sh_images/logo.png' %}" height="30" width="35"></a>
             <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'about_us' %}"><span class="fa fa-info fa-lg"></span>About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'contact_us' %}"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
                </ul>
                <span class="navbar-text ml-auto">
                    <a role="button" id="signupbutton" href="/">
                        <span class="fa fa-sign-out"></span>Sign out
                    </a>
                </span>
            </div> 
		</div>
	</nav>
</body>

shpro/shapp/templates/checkout.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://js.stripe.com/v3/"></script>

    <style>
    .StripeElement {
        box-sizing: border-box;

        height: 40px;

        padding: 10px 12px;

        border: 1px solid transparent;
        border-radius: 4px;
        background-color: white;

        box-shadow: 0 1px 3px 0 #e6ebf1;
        -webkit-transition: box-shadow 150ms ease;
        transition: box-shadow 150ms ease;
        }

        .StripeElement--focus {
        box-shadow: 0 1px 3px 0 #cfd7df;
        }

        .StripeElement--invalid {
        border-color: #fa755a;
        }

        .StripeElement--webkit-autofill {
        background-color: #fefde5 !important;
        }
    </style>

    <style type="text/css">
    #loader {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      width: 100%;
      background: rgba(0,0,0,0.75) url('{% static "sh_images/loading2.gif" %}') no-repeat center center;
      z-index: 10000;
    }
    </style>


</head>


<body>

<div class="container">
    <br><br><br>
    {% include '_flash_messages.html' %}
    <br>

    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rent-Days</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.book_name}}</td>
                        {% if cp.product.rent_days %}
                          <td>{{cp.product.rent_days}}</td>
                        {% else %}
                        <td>-</td>
                        {% endif %}
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="{% url 'checkout' %}" method="POST" id="payment-form">
                {% csrf_token %}
                
                {% for cp in cart.cartproduct_set.all %}
                <input type="hidden" value="{{cp.product.book_name}}" name="bookName">
                
                  {% if cp.product.rent_days %}
                    <input type="hidden" value="{{cp.product.rent_days}}" name="BooksDays">
                  {% endif %}

                {% endfor %}

               

                <div class="form-group">
                    <label for="id_ordered_by">Full Name *</label>
                    <input type="text" required class="form-control" name="ordered_by" maxlength="200" id="id_ordered_by" placeholder="Enter Full Name">
                </div>
                <div class="form-group">
                    <label for="id_shipping_address">Shipping Address *</label>
                    <input type="text" required name="shipping_address" maxlength="500" class="form-control" id="id_shipping_address" placeholder="Enter Shipping Address">
                </div>

                <div class="form-group">
                    <label for="id_mobile">Phone No *</label>
                    <input type="tel" min="0" maxlength="10" oninput="this.value =
                    !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null" name="mobile" class="form-control" id="id_mobile" placeholder="Enter Phone No">
                </div>

                <div class="form-group">
                    <label for="id_email">Email *</label>
                    <input type="email" autocomplete="email" required class="form-control" name="email" id="id_email" placeholder="Enter Email Address">
                </div>
                <br>
                  
                <div id="loader"></div>

                <div class="col-md-12">
                    <label for="card-element" style="color:#9f1959;"><br>
                        Credit or Debit and Master card accepted
                    </label>

                    <br>
                    <div id="card-element" class="StripeElement StripeElement--empty tab1">
                        <div class="__PrivateStripeElement tab1" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                            <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5065" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-a0b39ed02c7f668479dc8f00f24ca208.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;apiKey=pk_test_6NTdZNygDqQI3VAmrajQKqc700raAXo38d&amp;origin=http%3A%2F%2F127.0.0.1%3A8000&amp;referrer=http%3A%2F%2F127.0.0.1%3A8000%2Fpost_create%2F&amp;controllerId=__privateStripeController5061" title="Secure card payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; transform: translateZ(0px) !important; height: 19.2px;"></iframe>
                            <input required class="__PrivateStripeElement-input tab1" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                        </div>
                    </div>

                <!-- Used to display form errors. -->
                <div id="card-errors" role="alert"></div>
                <br>


                <center>
                    <button class="btn btn-primary" id="submit-all" value="Submit Payment" style="background-color: #8197f0!important;" type="submit">Submit</button>
                </center>
                </div>

            </form>
        </div>
    </div>


</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>

    // Create a Stripe client.
var stripe = Stripe('pk_test_6NTdZNygDqQI3VAmrajQKqc700raAXo38d');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.on('change', function(event) {
  var displayError = document.getElementById('card-errors');
  var spinner = $('#loader');
  if (event.error) {
    displayError.textContent = event.error.message;
    spinner.hide(event.error);
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  var spinner = $('#loader');
  spinner.show();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      var spinner = $('#loader');
      errorElement.textContent = result.error.message;
      spinner.hide(result.error);
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);
  // Submit the form

  form.submit();

}
</script>

</body>
</html>